version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models:/app/models
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  # Uncomment and configure these services as needed
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

  # postgres:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_USER: paksatalker
  #     POSTGRES_PASSWORD: paksatalker
  #     POSTGRES_DB: paksatalker
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
